# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andromeda Labs
tagline:          'A Developer Blog'
description:      'A developer blog about <strong>Android</strong>, <strong>Python</strong> and <strong>NodeJS</strong> by <a href="https://twitter.com/adnanbasarr" target="_blank">@adnanbasarr</a>.'
url:              http://andromedalabs.org
baseurl:          /

author:
  name:           'Adnan Basar'
  url:            https://twitter.com/adnanbasarr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adnbsr
